'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  CheckCircle2,
  Download,
  Eye,
  FileText,
  Clock,
  Copy,
  Check,
} from 'lucide-react';

interface SubmissionReceiptProps {
  documentTitle: string;
  wordCount: number;
  fileName: string;
  fileSize?: string;
  reportId: string;
  similarityScore?: number;
  aiScore?: number;
  onViewReport?: () => void;
}

export default function SubmissionReceipt({
  documentTitle,
  wordCount,
  fileName,
  fileSize,
  reportId,
  similarityScore,
  aiScore,
  onViewReport,
}: SubmissionReceiptProps) {
  const [copied, setCopied] = useState(false);

  const submissionId = `NW-${reportId.substring(0, 8).toUpperCase()}`;
  const timestamp = new Date().toLocaleString();

  // Create a notification record after receipt is shown
  useEffect(() => {
    async function createNotification() {
      try {
        await fetch('/api/notifications', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title: 'Submission Received',
            message: `Your document "${documentTitle}" has been successfully scanned. Similarity: ${(similarityScore ?? 0).toFixed(1)}%, AI: ${(aiScore ?? 0).toFixed(1)}%. Submission ID: ${submissionId}`,
            type: similarityScore !== undefined && similarityScore > 40 ? 'warning' : 'success',
          }),
        });
      } catch {
        // notification creation is best-effort
      }
    }
    createNotification();
  }, [documentTitle, similarityScore, aiScore, submissionId]);

  const handleDownloadReceipt = () => {
    const receipt = `
╔══════════════════════════════════════════════════╗
║           NigWrite Submission Receipt            ║
╠══════════════════════════════════════════════════╣
║                                                  ║
║  Submission ID:  ${submissionId.padEnd(28)}║
║  Date/Time:      ${timestamp.padEnd(28)}║
║                                                  ║
║  Document:       ${documentTitle.substring(0, 36).padEnd(28)}║
║  Word Count:     ${wordCount.toString().padEnd(28)}║
║  File Name:       ${fileName.substring(0, 36).padEnd(28)}║
║  File Size:       ${(fileSize || 'N/A').padEnd(28)}║
║                                                  ║
║  Similarity:     ${((similarityScore ?? 0).toFixed(1) + '%').padEnd(28)}║
║  AI Score:        ${((aiScore ?? 0).toFixed(1) + '%').padEnd(28)}║
║                                                  ║
╠══════════════════════════════════════════════════╣
║  Generated by NigWrite                          ║
║  Nigeria's Academic Integrity Platform            ║
║  Created by Wabi The Tech Nurse                   ║
╚══════════════════════════════════════════════════╝
`.trim();

    const blob = new Blob([receipt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NigWrite-Receipt-${submissionId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyId = () => {
    navigator.clipboard.writeText(submissionId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card className="border-[#008751]/30 overflow-hidden">
      <div className="bg-gradient-to-r from-[#008751] to-[#006b40] px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center">
            <CheckCircle2 className="h-7 w-7 text-white" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Submission Received!</h3>
            <p className="text-sm text-white/80">Your document has been successfully submitted for scanning.</p>
          </div>
        </div>
      </div>

      <CardContent className="pt-5 space-y-4">
        {/* Submission ID */}
        <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
          <div>
            <p className="text-xs text-muted-foreground">Submission ID</p>
            <p className="font-mono font-bold text-sm">{submissionId}</p>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCopyId}
            className="gap-1 text-xs"
          >
            {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
            {copied ? 'Copied!' : 'Copy'}
          </Button>
        </div>

        {/* Details Grid */}
        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-0.5">
            <p className="text-xs text-muted-foreground">Timestamp</p>
            <p className="text-sm font-medium">{timestamp}</p>
          </div>
          <div className="space-y-0.5">
            <p className="text-xs text-muted-foreground">Word Count</p>
            <p className="text-sm font-medium">{wordCount.toLocaleString()} words</p>
          </div>
          <div className="space-y-0.5 col-span-2">
            <p className="text-xs text-muted-foreground">Document Title</p>
            <p className="text-sm font-medium truncate">{documentTitle}</p>
          </div>
          <div className="space-y-0.5">
            <p className="text-xs text-muted-foreground">File Name</p>
            <p className="text-sm font-medium truncate">{fileName}</p>
          </div>
          <div className="space-y-0.5">
            <p className="text-xs text-muted-foreground">File Size</p>
            <p className="text-sm font-medium">{fileSize || 'N/A'}</p>
          </div>
        </div>

        {/* Scores */}
        {similarityScore !== undefined && aiScore !== undefined && (
          <div className="flex items-center gap-4 p-3 bg-muted/30 rounded-lg">
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Similarity:</span>
              <Badge className={
                similarityScore < 15
                  ? 'bg-emerald-100 text-emerald-700'
                  : similarityScore < 35
                    ? 'bg-amber-100 text-amber-700'
                    : 'bg-red-100 text-red-700'
              }>
                {similarityScore.toFixed(1)}%
              </Badge>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">AI:</span>
              <Badge className={
                aiScore < 15
                  ? 'bg-emerald-100 text-emerald-700'
                  : aiScore < 35
                    ? 'bg-purple-100 text-purple-700'
                    : 'bg-red-100 text-red-700'
              }>
                {aiScore.toFixed(1)}%
              </Badge>
            </div>
          </div>
        )}

        {/* Guidance */}
        {similarityScore !== undefined && (
          <div className={`p-3 rounded-lg text-sm ${
            similarityScore < 15
              ? 'bg-emerald-50 border border-emerald-200 text-emerald-700'
              : similarityScore < 35
                ? 'bg-amber-50 border border-amber-200 text-amber-700'
                : 'bg-red-50 border border-red-200 text-red-700'
          }`}>
            <p className="font-medium">
              {similarityScore < 15
                ? '✅ Excellent! Your document shows very low similarity.'
                : similarityScore < 35
                  ? '⚠️ Minor similarity detected. Review flagged sections and add citations.'
                  : '🔴 High similarity detected. Significant revision recommended before submitting.'}
            </p>
          </div>
        )}

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-2 pt-2">
          {onViewReport && (
            <Button
              onClick={onViewReport}
              className="gap-2 bg-[#008751] hover:bg-[#006b40]"
            >
              <Eye className="h-4 w-4" />
              View Report
            </Button>
          )}
          <Button variant="outline" onClick={handleDownloadReceipt} className="gap-2">
            <Download className="h-4 w-4" />
            Download Receipt
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
