/**
 * NigWrite - Submission Receipt Component
 * Shown after successful submission with confirmation details.
 */

'use client';

import { useEffect, useState } from 'react';
import {
  CheckCircle2,
  Download,
  Clock,
  FileText,
  Hash,
  BookOpen,
  Copy,
  Check,
  AlertCircle,
} from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

interface SubmissionReceiptProps {
  submissionId: string;
  documentTitle: string;
  assignmentTitle: string;
  timestamp: string;
  wordCount?: number;
  fileName?: string;
  fileSize?: string;
  onClose?: () => void;
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

export function SubmissionReceipt({
  submissionId,
  documentTitle,
  assignmentTitle,
  timestamp,
  wordCount,
  fileName,
  fileSize,
  onClose,
}: SubmissionReceiptProps) {
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');

  // Create notification for the student
  useEffect(() => {
    const createNotification = async () => {
      try {
        await fetch('/api/notifications', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title: 'Submission Received',
            message: `Your submission "${documentTitle}" for "${assignmentTitle}" has been received. Submission ID: ${submissionId}`,
            type: 'success',
          }),
        });
      } catch {
        // silent
      }
    };
    createNotification();
  }, [submissionId, documentTitle, assignmentTitle]);

  const handleDownloadReceipt = () => {
    const receiptText = [
      '═══════════════════════════════════════════════════',
      '           NIGWRITE SUBMISSION RECEIPT',
      '═══════════════════════════════════════════════════',
      '',
      `Submission ID:   ${submissionId}`,
      `Timestamp:       ${formatDate(timestamp)}`,
      `Document Title:  ${documentTitle}`,
      `Assignment:      ${assignmentTitle}`,
      '',
      ...(wordCount ? [`Word Count:      ${wordCount.toLocaleString()}`] : []),
      ...(fileName ? [`File Name:        ${fileName}`] : []),
      ...(fileSize ? [`File Size:        ${fileSize}`] : []),
      '',
      '───────────────────────────────────────────────────',
      'STATUS: RECEIVED',
      '',
      'Your submission has been received and is being',
      'processed. You will receive a notification once',
      'the plagiarism scan is complete.',
      '',
      '───────────────────────────────────────────────────',
      'Generated by NigWrite Academic Integrity Platform',
      `Generated at: ${formatDate(new Date().toISOString())}`,
      '═══════════════════════════════════════════════════',
    ].join('\n');

    try {
      const blob = new Blob([receiptText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `NigWrite-Receipt-${submissionId}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      setError('Failed to download receipt');
      setTimeout(() => setError(''), 3000);
    }
  };

  const handleCopyId = async () => {
    try {
      await navigator.clipboard.writeText(submissionId);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // silent
    }
  };

  return (
    <div className="max-w-md mx-auto">
      <Card className="border-emerald-200 overflow-hidden">
        {/* Success header */}
        <div className="bg-gradient-to-r from-emerald-500 to-[#008751] px-6 py-4 text-center">
          <CheckCircle2 className="h-10 w-10 text-white mx-auto mb-2" />
          <h3 className="text-lg font-bold text-white">Submission Received!</h3>
          <p className="text-emerald-100 text-sm">
            Your document has been successfully submitted
          </p>
        </div>

        <CardContent className="pt-5 pb-5 space-y-4">
          {/* Receipt details */}
          <div className="space-y-3">
            <div className="flex items-start gap-3">
              <Hash className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <div className="text-xs text-muted-foreground">Submission ID</div>
                <div className="flex items-center gap-1.5">
                  <code className="text-xs font-mono bg-gray-100 px-1.5 py-0.5 rounded">
                    {submissionId.substring(0, 20)}...
                  </code>
                  <button onClick={handleCopyId} className="text-muted-foreground hover:text-foreground">
                    {copied ? <Check className="h-3 w-3 text-emerald-600" /> : <Copy className="h-3 w-3" />}
                  </button>
                </div>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <Clock className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
              <div>
                <div className="text-xs text-muted-foreground">Timestamp</div>
                <div className="text-sm">{formatDate(timestamp)}</div>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <FileText className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
              <div>
                <div className="text-xs text-muted-foreground">Document</div>
                <div className="text-sm font-medium">{documentTitle}</div>
                {fileName && (
                  <div className="text-xs text-muted-foreground">
                    {fileName} {fileSize && `(${fileSize})`}
                  </div>
                )}
              </div>
            </div>

            <div className="flex items-start gap-3">
              <BookOpen className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
              <div>
                <div className="text-xs text-muted-foreground">Assignment</div>
                <div className="text-sm">{assignmentTitle}</div>
              </div>
            </div>

            {wordCount && (
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">
                  {wordCount.toLocaleString()} words
                </span>
              </div>
            )}
          </div>

          {/* Divider */}
          <div className="border-t" />

          {/* Confirmation message */}
          <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3 text-center">
            <p className="text-sm text-emerald-700">
              Your submission is now being processed. You will receive a
              notification once the plagiarism scan is complete.
            </p>
          </div>

          {/* Error */}
          {error && (
            <div className="flex items-center gap-2 text-red-600 text-xs">
              <AlertCircle className="h-3 w-3" />
              {error}
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              className="flex-1 gap-1.5 text-xs"
              onClick={handleDownloadReceipt}
            >
              <Download className="h-3.5 w-3.5" />
              Download Receipt
            </Button>
            {onClose && (
              <Button
                size="sm"
                className="flex-1 gap-1.5 text-xs bg-[#008751] hover:bg-[#006b40]"
                onClick={onClose}
              >
                Done
              </Button>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
